export type SchemaNode = {
  kind: "object" | "array" | "map" | "string" | "number" | "boolean" | "any";
  ref?: string;
  item?: SchemaNode;
  value?: SchemaNode;
};

export type SchemaField = { key: string; node: SchemaNode; owner?: string; goName?: string; goType?: string; comment?: string; deprecated?: boolean };
export type ConfigSchema = { root: SchemaNode; definitions: Record<string, { fields: SchemaField[] }> };
export type ConfigDocument = Record<string, unknown>;

export function createInitialConfig(): ConfigDocument {
  // Defaults come from the Admin API's pinned eRPC binary.  An empty object
  // is the intentional sparse override document used before that snapshot
  // has been fetched.
  return {};
}

/** Merge an operator override document onto the effective eRPC defaults. */
export function materializeEffectiveConfig(overrides: ConfigDocument, defaults: ConfigDocument, _schema?: ConfigSchema): ConfigDocument {
  return mergeValues(defaults, overrides) as ConfigDocument;
}

/**
 * Return only values that differ from the effective defaults.  Existing
 * overrides are supplied so fields unknown to this Web build survive a
 * round-trip unchanged.
 */
export function extractOverrides(effective: ConfigDocument, defaults: ConfigDocument, schema?: ConfigSchema, existingOverrides: ConfigDocument = {}): ConfigDocument {
  // The form only knows the schema generated by this build.  Hydrate opaque
  // fields from the previous sparse document into items that still exist in
  // the edited effective document before diffing; this preserves newer eRPC
  // fields without resurrecting rows the operator deleted.
  const hydrated = schema ? mergeOpaqueFields(effective, existingOverrides, schema.root, schema) : effective;
  const known = diffValues(hydrated, defaults);
  return mergeUnknownOverrides(known, existingOverrides, schema?.root, schema);
}

export type FieldState = "system-default" | "custom" | "unset";

export function fieldState(path: (string | number)[], overrides: ConfigDocument, defaults: ConfigDocument): FieldState {
  const override = valueAtPath(overrides, path);
  if (override.exists) return "custom";
  return valueAtPath(defaults, path).exists ? "system-default" : "unset";
}

export function valueAtPath(value: unknown, path: (string | number)[]): { exists: boolean; value: unknown } {
  let current: unknown = value;
  for (const part of path) {
    if (Array.isArray(current) && typeof part === "number" && part >= 0 && part < current.length) current = current[part];
    else if (isRecord(current) && Object.hasOwn(current, String(part))) current = current[String(part)];
    else return { exists: false, value: undefined };
  }
  return { exists: true, value: current };
}

/** Remove one override path and prune now-empty parent objects. */
export function deleteOverride(overrides: ConfigDocument, path: (string | number)[]): ConfigDocument {
  const result = structuredClone(overrides) as ConfigDocument;
  if (path.length === 0) return {};
  let current: any = result;
  for (let index = 0; index < path.length - 1; index += 1) {
    const part = path[index];
    if (current == null || !Object.hasOwn(current, String(part))) return result;
    current = current[part as any];
  }
  const last = path[path.length - 1];
  if (Array.isArray(current) && typeof last === "number") current.splice(last, 1);
  else if (isRecord(current)) delete current[String(last)];
  pruneEmpty(result);
  return result;
}

/** Apply an Ant Design changed-values fragment to a sparse override object. */
export function applyFormChanges(overrides: ConfigDocument, changedValues: ConfigDocument, defaults: ConfigDocument, schema?: ConfigSchema): ConfigDocument {
  const effective = materializeEffectiveConfig(overrides, defaults, schema);
  const changedEffective = mergeValues(effective, changedValues) as ConfigDocument;
  return extractOverrides(changedEffective, defaults, schema, overrides);
}

export function toFormDocument(value: ConfigDocument, schema: ConfigSchema): ConfigDocument {
  return transformToForm(value, schema.root, schema, true) as ConfigDocument;
}

export function fromFormDocument(value: ConfigDocument, schema: ConfigSchema): ConfigDocument {
  return transformFromForm(value, schema.root, schema, true) as ConfigDocument;
}

export function normalizeSvmStatePollerDebounce(value: unknown): unknown {
  if (typeof value === "number" && Number.isFinite(value)) return `${value}ms`;
  if (typeof value !== "string") return value;
  const text = value.trim();
  return /^\d+(?:\.\d+)?$/.test(text) ? `${text}ms` : value;
}

export function mergeKnownConfig(original: ConfigDocument, edited: ConfigDocument, schema: ConfigSchema): ConfigDocument {
  return mergeNode(original, edited, schema.root, schema) as ConfigDocument;
}

export function fieldsFor(node: SchemaNode, schema: ConfigSchema): SchemaField[] {
  return node.ref ? schema.definitions[node.ref]?.fields || [] : [];
}

function transformToForm(value: unknown, node: SchemaNode, schema: ConfigSchema, root = false): unknown {
  if (value === undefined || value === null) return value;
  if (node.kind === "object") {
    const source = record(value);
    const result: ConfigDocument = {};
    for (const field of fieldsFor(node, schema)) {
      if (Object.hasOwn(source, field.key)) result[field.key] = transformToForm(source[field.key], field.node, schema);
    }
    return root || Object.keys(result).length > 0 ? result : undefined;
  }
  if (node.kind === "array") return Array.isArray(value) ? value.map((item) => transformToForm(item, node.item || { kind: "any" }, schema)) : undefined;
  if (node.kind === "map") return Object.entries(record(value)).map(([key, item]) => ({ key, value: transformToForm(item, node.value || { kind: "any" }, schema) }));
  return value;
}

function transformFromForm(value: unknown, node: SchemaNode, schema: ConfigSchema, root = false): unknown {
  if (value === undefined || value === null || value === "") return undefined;
  if (node.kind === "object") {
    const source = record(value);
    const result: ConfigDocument = {};
    for (const field of fieldsFor(node, schema)) {
      let next = transformFromForm(source[field.key], field.node, schema);
      if (field.owner === "SvmNetworkConfig" && field.key === "statePollerDebounce") next = normalizeSvmStatePollerDebounce(next);
      // eRPC treats both network scope fields as mutually exclusive by
      // presence. An empty list means "no restriction" in the form, so omit
      // it instead of emitting `onlyNetworks: []` and `ignoreNetworks: []`.
      if (next !== undefined && !(field.node.kind === "array" && (field.key === "onlyNetworks" || field.key === "ignoreNetworks") && Array.isArray(next) && next.length === 0)) {
        result[field.key] = next;
      }
    }
    // Form.List registers an empty strategies array even when no auth
    // strategy was added. An empty AuthConfig is invalid in eRPC, so omit the
    // optional object entirely until it contains a real strategy.
    if (node.ref === "AuthConfig" && Array.isArray(result.strategies) && result.strategies.length === 0) return undefined;
    return root || Object.keys(result).length > 0 ? result : undefined;
  }
  if (node.kind === "array") return Array.isArray(value) ? value.map((item) => transformFromForm(item, node.item || { kind: "any" }, schema)).filter((item) => item !== undefined) : undefined;
  if (node.kind === "map") {
    if (!Array.isArray(value)) return undefined;
    const result: ConfigDocument = {};
    for (const entry of value) {
      const item = record(entry);
      const key = String(item.key || "").trim();
      const next = transformFromForm(item.value, node.value || { kind: "any" }, schema);
      if (key && next !== undefined) result[key] = next;
    }
    return result;
  }
  return value;
}

function mergeNode(original: unknown, edited: unknown, node: SchemaNode, schema: ConfigSchema): unknown {
  if (edited === undefined) return undefined;
  if (node.kind === "object") {
    const result = structuredClone(record(original));
    const source = record(edited);
    for (const field of fieldsFor(node, schema)) {
      if (!Object.hasOwn(source, field.key)) {
        delete result[field.key];
        continue;
      }
      const next = mergeNode(record(original)[field.key], source[field.key], field.node, schema);
      if (next === undefined) delete result[field.key];
      else result[field.key] = next;
    }
    return result;
  }
  if (node.kind === "array") {
    if (!Array.isArray(edited)) return undefined;
    const before = Array.isArray(original) ? original : [];
    return edited.map((item, index) => mergeNode(before[index], item, node.item || { kind: "any" }, schema));
  }
  if (node.kind === "map") {
    const result: ConfigDocument = {};
    const before = record(original);
    for (const [key, value] of Object.entries(record(edited))) result[key] = mergeNode(before[key], value, node.value || { kind: "any" }, schema);
    return result;
  }
  return edited;
}

function record(value: unknown): ConfigDocument {
  return value && typeof value === "object" && !Array.isArray(value) ? value as ConfigDocument : {};
}

function isRecord(value: unknown): value is ConfigDocument {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function mergeValues(base: unknown, override: unknown): unknown {
  if (!isRecord(base) || !isRecord(override)) return structuredClone(override);
  const result: ConfigDocument = structuredClone(base);
  for (const [key, value] of Object.entries(override)) result[key] = Object.hasOwn(result, key) ? mergeValues(result[key], value) : structuredClone(value);
  return result;
}

function mergeOpaqueFields(effective: unknown, existing: unknown, node: SchemaNode, schema: ConfigSchema): unknown {
  if (isRecord(effective)) {
    const result = structuredClone(effective) as ConfigDocument;
    if (!isRecord(existing)) return result;
    for (const [key, value] of Object.entries(existing)) {
      const field = node.ref ? fieldsFor(node, schema).find((item) => item.key === key) : undefined;
      if (!field) {
        if (!Object.hasOwn(result, key)) result[key] = structuredClone(value);
        continue;
      }
      if (field.deprecated) {
        if (Object.hasOwn(result, key) === false) result[key] = structuredClone(value);
        continue;
      }
      if (!Object.hasOwn(result, key)) continue;
      if (field.node.kind === "object") result[key] = mergeOpaqueFields(result[key], value, field.node, schema);
      else if (field.node.kind === "array" && Array.isArray(result[key]) && Array.isArray(value)) result[key] = mergeOpaqueArray(result[key], value, field.node.item, schema);
      else if (field.node.kind === "map" && isRecord(result[key]) && isRecord(value)) {
        const current = result[key] as ConfigDocument;
        for (const mapKey of Object.keys(current)) {
          if (Object.hasOwn(value, mapKey)) current[mapKey] = mergeOpaqueFields(current[mapKey], value[mapKey], field.node.value || { kind: "any" }, schema);
        }
      }
    }
    return result;
  }
  return structuredClone(effective);
}

function mergeOpaqueArray(effective: unknown[], existing: unknown[], itemNode: SchemaNode | undefined, schema: ConfigSchema): unknown[] {
  const used = new Set<number>();
  const allowPositionalFallback = effective.length === existing.length;
  return effective.map((item, index) => {
    const existingIndex = findExistingArrayItem(item, existing, index, used, allowPositionalFallback);
    if (existingIndex < 0) return structuredClone(item);
    used.add(existingIndex);
    return mergeArrayItemUnknown(item, existing[existingIndex], itemNode, schema);
  });
}

function diffValues(value: unknown, defaults: unknown): unknown {
  if (Object.is(value, defaults)) return undefined;
  if (Array.isArray(value) && Array.isArray(defaults)) {
    return configDocumentsEqual(value, defaults) ? undefined : structuredClone(value);
  }
  if (isRecord(value) && isRecord(defaults)) {
    const result: ConfigDocument = {};
    for (const [key, item] of Object.entries(value)) {
      const next = diffValues(item, defaults[key]);
      if (next !== undefined) result[key] = next;
    }
    return Object.keys(result).length > 0 ? result : undefined;
  }
  return structuredClone(value);
}

function mergeUnknownOverrides(known: unknown, existing: unknown, node?: SchemaNode, schema?: ConfigSchema): ConfigDocument {
  const result = isRecord(known) ? structuredClone(known) : {};
  if (!isRecord(existing)) return result;
  for (const [key, value] of Object.entries(existing)) {
    const field = node?.ref && schema ? fieldsFor(node, schema).find((item) => item.key === key) : undefined;
    if (!field) {
      if (!Object.hasOwn(result, key)) result[key] = structuredClone(value);
      continue;
    }
    if (field.deprecated) {
      if (!Object.hasOwn(result, key)) result[key] = structuredClone(value);
      continue;
    }
    if (field.node.kind === "object" && isRecord(value)) {
      const nested = mergeUnknownOverrides(result[key], value, field.node, schema);
      if (Object.keys(nested).length > 0) result[key] = nested;
      else delete result[key];
    } else if (field.node.kind === "array" && Array.isArray(value)) {
      // The edited array is authoritative: an item removed in the form must
      // not be re-added just because it still exists in the old sparse
      // override. Match by a stable identity when possible so unknown fields
      // from a newer eRPC build follow the item after reorder/delete.
      if (Array.isArray(result[key])) {
        const current = result[key] as unknown[];
        const used = new Set<number>();
        result[key] = current.map((item, index) => {
          const existingIndex = findExistingArrayItem(item, value, index, used, current.length === value.length);
          if (existingIndex < 0) return item;
          used.add(existingIndex);
          return mergeArrayItemUnknown(item, value[existingIndex], field.node.item, schema);
        });
      }
    }
  }
  return result;
}

function mergeArrayItemUnknown(current: unknown, existing: unknown, itemNode: SchemaNode | undefined, schema?: ConfigSchema): unknown {
  if (!isRecord(existing)) return current === undefined ? structuredClone(existing) : current;
  if (!itemNode || itemNode.kind !== "object") return current === undefined ? structuredClone(existing) : current;
  return mergeUnknownOverrides(current, existing, itemNode, schema);
}

function findExistingArrayItem(current: unknown, existing: unknown[], index: number, used: Set<number>, allowPositionalFallback: boolean): number {
  const identity = arrayItemIdentity(current);
  if (identity !== undefined) {
    const exact = existing.findIndex((candidate, candidateIndex) => !used.has(candidateIndex) && arrayItemIdentity(candidate) === identity);
    if (exact >= 0) return exact;
    if (allowPositionalFallback && index < existing.length && !used.has(index)) return index;
    return -1;
  }
  if (!allowPositionalFallback) return -1;
  if (index < existing.length && !used.has(index) && arrayItemIdentity(existing[index]) === undefined) return index;
  return existing.findIndex((candidate, candidateIndex) => !used.has(candidateIndex) && arrayItemIdentity(candidate) === undefined);
}

function arrayItemIdentity(value: unknown): string | undefined {
  if (!isRecord(value)) return undefined;
  for (const key of ["id", "key", "name", "alias", "endpoint", "chainId", "networkId", "projectId"]) {
    const item = value[key];
    if (typeof item === "string" || typeof item === "number") {
      const text = String(item).trim();
      if (text) return `${key}:${text}`;
    }
  }
  const evmChainId = record(value.evm).chainId;
  if (typeof evmChainId === "number" && evmChainId > 0) return `evm.chainId:${evmChainId}`;
  const svm = record(value.svm);
  const svmChain = String(svm.chain || "").trim();
  const svmCluster = String(svm.cluster || "").trim();
  if (svmChain || svmCluster) return `svm:${svmChain}:${svmCluster}`;
  return undefined;
}

export function configDocumentsEqual(left: unknown, right: unknown): boolean {
  if (Object.is(left, right)) return true;
  if (Array.isArray(left) && Array.isArray(right)) return left.length === right.length && left.every((item, index) => configDocumentsEqual(item, right[index]));
  if (isRecord(left) && isRecord(right)) {
    const leftKeys = Object.keys(left);
    const rightKeys = Object.keys(right);
    return leftKeys.length === rightKeys.length && leftKeys.every((key) => Object.hasOwn(right, key) && configDocumentsEqual(left[key], right[key]));
  }
  return false;
}

function pruneEmpty(value: unknown): boolean {
  if (!isRecord(value)) return false;
  for (const [key, item] of Object.entries(value)) {
    if (isRecord(item) && pruneEmpty(item) && Object.keys(item).length === 0) delete value[key];
  }
  return Object.keys(value).length === 0;
}
